### ISSUE TITLE
The heapster-poseidon image is only available for x86 arch

### ISSUE THREAD

**Issue by marceloamaral** [kubernetes-sigs/poseidon#111]
I am trying to run poseidon on PowerPC machines. However, I didn't find the source code of the image shivramsrivastava/heapster-poseidon, so that I cannot create an image for PowerPC arch.

In this case, could you please share the modified heapster source (heapster-poseidon), or generate the image for ppc64le arch?

What is the difference between the shivramsrivastava/heapster-poseidon and a regular heapster image?

**Comment by shivramsrivastava** [comment]
@marceloamaral 
Sorry for the confusion, we had updated about the heapster sink in the developer's readme [here](https://github.com/kubernetes-sigs/poseidon/blob/master/docs/devel/README.md#developer-setup).

>  However, I didn't find the source code of the image shivramsrivastava/heapster-Poseidon, 

You can find the sink code [here](https://github.com/camsas/heapster).

> In this case, could you please share the modified heapster source (heapster-poseidon), or generate the image for ppc64le arch?

We are not planning to support heapster sink anymore in Poseidon.
Since heapster will be depreciated soon in kubernetes, we don't want to invest on that, and we are looking for other options, like using the metrics servers as the community suggests.


> What is the difference between the shivramsrivastava/heapster-poseidon and a regular heapster image?

The main difference is in regular heapster we dont have a sink for 'Poseidon', where as in our heapster image we have a sink to push metrics data to 'Poseidon'.

> Why we need cluster metrics in 'Poseidon'?

The main the reason is since 'Poseidon' will not be the only 'Scheduler' running in a K8S cluster.
There could be other scheduler's which could schedule 'Pods'.
If 'Firmament' is not aware of the changing state of the cluster, it could take bad scheduling decisions.
So 'Poseidon-Sink' in heapster is used to update the running cluster info to the knowledge-base of firmament. This knowledgebase is consulted every time a scheduling decision is taken.

> Alternate for the Heapster sink?

The firmament code in the [Huawei-PaaS](https://github.com/Huawei-PaaS/firmament/tree/dev) dev-branch has fix to circumvent this problem.
You can use that code and you dont have to use the heapster image.
The only draw back is if you use that you need to make sure 'Firmament' is the only scheduler working/running, you can also have the default scheduler's running but it should not schedule any 'Pods'.

**Comment by deepak-vij** [comment]
Leaving this open for the time being, we will get to it when possible.
