### ISSUE TITLE
Benchmark was done using which flow cost model?

### ISSUE THREAD

**Issue by chauncey-77** [kubernetes-sigs/poseidon#184]
Hi, I want to know which firmament cost model you chose to do the benchmarking. Please tell me, thanks.
Cost models can be found here [cost models](https://github.com/huawei-cloudnative/firmament).

**Comment by deepak-vij** [comment]
In order to do apple versus apple comparisons with Kubernetes, all of our Poseidon/Firmament work was using our brand new multi-dimensional CPU-Memory cost model. All other original Firmament cost models are all single dimensional. Doing multi-dimensional graph programming has some challenges and complexities to deal with, we had to find ways around it in few instances.

**Comment by chauncey-77** [comment]
thanks for your reply. thank you.
