### ISSUE TITLE
State where we are and revise roadmap to help the project better moving forward

### ISSUE THREAD

**Issue by kevin-wangzefeng** [kubernetes-sigs/poseidon#60]
As discussed yesterday, to help the project better moving forward, we shall:

**1. State where we are** (with details)
+ Add description of the project development stage -- I'd say alpha or pre-alpha? 
Since we not yet pass all scheduling conformance tests.

+ Figure out how far away behind the default scheduler at functionality wise. 
The best way to do is run scheduling e2e test from the core repo (with arg `--ginkgo.focus="sig-scheduling"`),
and see how many tests fail. 

+ Add CI status indicator
Just a basic thing every project shall do. To better track project healthy.

**2. Revise roadmap and better backlog grooming**

+ It's almost mid May now, while some of the items supposed to be done from initial roadmap still not yet implemented. 
+ There's no milestone set, nor any priority labels set on issues, we shall add them.

**3. Do other things...** that help improve contributor experience

Comments are always welcome.

**Comment by deepak-vij** [comment]
@kevin-wangzefeng thanks for your feedback. Roadmap items timelines which we initially planned got thrown off due to time we spent in resolving test.infra set up related issues. In any case, we will revise the timelines and reflect the exact  timelines shortly.

I agree with your other suggestions too, we will incorporate your suggestions as we move forward. Thanks.

**Comment by deepak-vij** [comment]
@kevin-wangzefeng we have already incorporated most of your suggestions in our repo. Shiva is in the process of enabling CI status indicator from test.grid.
  
In regards to running e2e tests against K8S core, current setup is hardwired for running these tests using default scheduler. We would need to repurpose the test script so that these tests run using Poseidon/Firmament scheduler instead. This is something we did discuss that during our daily team meeting. We are planning to do this exercise in local cluster environment. I will also create a separate issue to track this further.

In the meanwhile, for affinity/anti-affinity work, we are going to extract all relevant test cases from core and ensure that they are successful within our Poseidon/Firmament scheduling environment.

/cc @shivramsrivastava @m1093782566

**Comment by deepak-vij** [comment]
Hi Kevin, this is to let you know that Shiva has addressed the CI status issue you raised earlier. see the following issue for more details.

https://github.com/kubernetes-sigs/poseidon/issues/62

**Comment by kevin-wangzefeng** [comment]
Cool :+1:

**Comment by kevin-wangzefeng** [comment]
> In regards to running e2e tests against K8S core, current setup is hardwired for running these tests using default scheduler. We would need to repurpose the test script so that these tests run using Poseidon/Firmament scheduler instead. This is something we did discuss that during our daily team meeting. We are planning to do this exercise in local cluster environment. I will also create a separate issue to track this further.

Actually you can:
1. spin up a k8s cluster with whatever scripts you use
2. run firmament and poseidon as pods (probably deployments later on) on the cluster
3. add a mutating admission control webhook that sets every pod.scheduler-name to Poseidon/Firmament scheduler

> In the meanwhile, for affinity/anti-affinity work, we are going to extract all relevant test cases from core and ensure that they are successful within our Poseidon/Firmament scheduling environment.

With steps above done, I'd suggest have different tests in this project to avoid duplication.

**Comment by kevin-wangzefeng** [comment]
Project status and roadmap have been revised, closing this issue.
/close
